name: Stage

on:
  schedule:
    # Runs Mon-Fri at 16:00 UTC ( 12:00 EST )
    - cron: "0 16 * * 1-5"

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main to staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: staging
          github_token: ${{ github.token }}
          message: '[Automated] Merged main into staging'
