name: Stage

on:
  schedule:
    - cron: "45 16 * * *"

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main to staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: staging
          github_token: ${{ github.token }}
          message: '[Automated] Merged main into staging'
