name: Sync

on:
  pull_request:
    branches:
      - '*'
      - '!dev'
      - '!staging'
      - '!prod'
    types:
      - closed

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main to dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: dev
          github_token: ${{ github.token }}
          message: '[Automated] Merged main into target dev'
