name: Test

on:
  pull_request:
    types:
      - closed

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main to dev
        run: echo "Testing..."
